### ISSUE TITLE
rb test case is missing

### ISSUE THREAD

**Issue by LJWatson** [ThePacielloGroup/AT-browser-tests#19]
The link from the table returns a 404.

**Comment by LJWatson** [comment]
Also test cases for rp, rt, rtc, ruby, samp, script, section, small, span, strong, style, sup, sub, svg, template, time and title are missing/return 404.

**Comment by scottaohara** [comment]
I've gone through and cleaned up all the broken links, and links to older versions of element specs, so we can close this issue.
