### ISSUE TITLE
test case batch 2

### ISSUE THREAD

**Issue by stevefaulkner** [ThePacielloGroup/AT-browser-tests#2]
note: bunch of tests i created previously, may be useful http://stevefaulkner.github.io/html-mapping-tests/browser-tests/index.html + https://github.com/stevefaulkner/HTML5accessibility/tree/gh-pages/tests
- col + colgroup , hook up with Matthew and re-use his test case for table etc.
- data
- datalist
- dd + dl + dt
- del + ins
- details + summary test in chrome (firefox not implemented)
- dfn
- dialog test in chrome (firefox not implemented)
- div
- em
- embed
- fieldset +legend
- figcaption + figure
- figure without figcaption
- footer
- form
- h1 to h6 single test file
- head
- header
- hr
- html
- i
- iframe (with/without title attribute)
- img

**Comment by LJWatson** [comment]
The datalist element is not rendered in itsown right. Do we want to include it as part of a widget?
http://www.w3.org/TR/html/forms.html#the-datalist-element
