### ISSUE TITLE
Datalist role not spoken

### ISSUE THREAD

**Issue by allanj-uaag** [ThePacielloGroup/AT-browser-tests#22]
Using FF and Jaws16 
datalist example 
the edit box has a role of edit
was able to clue user to functionality by adding a role="combobox" or role="listbox" to the <input>
jaws instructions on combobox say "use arrow keys to change the selection"
first down arrow says nothing
second down arrow reads first item in datalist
ENTER selects the item in the list
jaws reads label of the control, role and instructions, and contents of the control.
if there is content other than the placeholder text you cannot interact with the datalist.
you must delete the contents of the edit box, then the place holder text appears, and the arrowkeys will allow navigation of the datalist. if anything else (other than placeholder text) is in the editbox, the up/down arrows will not allow navigation on the list.
special case:
in the example, if I tab into the editbox and type a "g" or an "r" then the arrow keys will work to select only the items on the list that begin with that letter. However, when I type a "g" the list drops down (indicating I can use the arrow keys to select), there is no aural indicator that the list dropped down (change of state?)

also, tested the fallback example with the <select> embedded within the <datalist> provided in the http://www.w3.org/TR/html/forms.html#the-datalist-element
fallback content was not revealed to the user.

**Comment by allanj-uaag** [comment]
all of the above is also true if I add role=listbox

**Comment by scottaohara** [comment]
There have been some improvements with this issue with FireFox 56 + JAWS 18, as JAWS at least announces that the text input has a popup.  But many of the points raised here are still valid.

I've opened a new issue over on the [Freedom Scientific - VFO Standards Support bug tracker](https://github.com/FreedomScientific/VFO-standards-support/issues/11) to re-surface this issue, so I will close this one here.

Thanks!
