### ISSUE TITLE
The Blockquote element needs to be tested with the cite attribute

### ISSUE THREAD

**Issue by Menelion** [ThePacielloGroup/AT-browser-tests#64]
when testing the `blockquote` element, an important test is missing: there is no test case with the `cite` attribute that indicates the source of the quote.  
JAWS supports this well.  
I would like to contribute the corresponding test. Do I also need to post the audio? Should I modify the text and/or audio for the blockquote test?  
Thanks!

**Comment by scottaohara** [comment]
Hi @Menelion 

Feel free to submit a PR.  If you can provide an audio sample, that'd be great.  But if that's an issue, don't let it stop you.

Thanks!
